apiVersion: v1
kind: Service
metadata:
  name: ejemplo-k8s-service
spec:
  type: NodePort
  selector:
    app: ejemplo-k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001